<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-CJN9AFV" failures="1" tests="5" name="com.thetestingacademy.tests.vwo.pageObjectModelTC.TestVWOLogin_05_TakeScreen_Retry_Prop_Improved_POM" time="39.858" errors="0" timestamp="2025-10-09T23:04:55 IST" skipped="3">
  <testcase classname="com.thetestingacademy.tests.vwo.pageObjectModelTC.TestVWOLogin_05_TakeScreen_Retry_Prop_Improved_POM" name="testFail" time="7.529">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.thetestingacademy.tests.vwo.pageObjectModelTC.TestVWOLogin_05_TakeScreen_Retry_Prop_Improved_POM.testFail(TestVWOLogin_05_TakeScreen_Retry_Prop_Improved_POM.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
    <system-out>
      <![CDATA[<a href='failure_screenshots/testFail_09_10_2025_11_04_45.png'> Screenshot</a>]]>
    </system-out>
  </testcase> <!-- testFail -->
  <testcase classname="com.thetestingacademy.tests.vwo.pageObjectModelTC.TestVWOLogin_05_TakeScreen_Retry_Prop_Improved_POM" name="testFail" time="8.499">
    <skipped/>
  </testcase> <!-- testFail -->
  <testcase classname="com.thetestingacademy.tests.vwo.pageObjectModelTC.TestVWOLogin_05_TakeScreen_Retry_Prop_Improved_POM" name="testFail" time="7.707">
    <skipped/>
  </testcase> <!-- testFail -->
  <testcase classname="com.thetestingacademy.tests.vwo.pageObjectModelTC.TestVWOLogin_05_TakeScreen_Retry_Prop_Improved_POM" name="testFail" time="8.095">
    <skipped/>
  </testcase> <!-- testFail -->
  <testcase classname="com.thetestingacademy.tests.vwo.pageObjectModelTC.TestVWOLogin_05_TakeScreen_Retry_Prop_Improved_POM" name="testPass" time="8.028"/>
  <system-out>
    <![CDATA[<a href='failure_screenshots/testFail_09_10_2025_11_04_45.png'> Screenshot</a>]]>
  </system-out>
</testsuite> <!-- com.thetestingacademy.tests.vwo.pageObjectModelTC.TestVWOLogin_05_TakeScreen_Retry_Prop_Improved_POM -->
